services:
  db:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: electrotrack
    ports:
      - "5433:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: