-- Enable Row Level Security
ALTER TABLE users
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE items
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE item_locations
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE attachments
    ENABLE ROW LEVEL SECURITY;